var searchData=
[
  ['bestflightairporttoairport_8',['bestFlightAirportToAirport',['../classApplication.html#aa4ee6ae860a9ce998ca7941d09021847',1,'Application::bestFlightAirportToAirport(const std::string &amp;airport1, const std::string &amp;airport2)'],['../classApplication.html#a2074349c9e85a0628c7d1189ddeddda9',1,'Application::bestFlightAirportToAirport(const std::string &amp;airport1, const std::string &amp;airport2, const std::vector&lt; Airline &gt; &amp;forbidden)']]],
  ['bestflightairporttocity_9',['bestFlightAirportToCity',['../classApplication.html#ab5a0af7d8204373ac0e99d3e0b5fb49d',1,'Application::bestFlightAirportToCity(const std::string &amp;airport, const std::string &amp;city, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a3eedaf8425cafbe4b4997251b42d56e4',1,'Application::bestFlightAirportToCity(const std::string &amp;airport, const std::string &amp;city)']]],
  ['bestflightairporttolocation_10',['bestFlightAirportToLocation',['../classApplication.html#a07f32efc8db59f1932bda5a9b6cf08bc',1,'Application::bestFlightAirportToLocation(const std::string &amp;airport, const long double &amp;latitude, const long double &amp;longitude, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a11ce361d27ce3e460c53c1fe0eb936e5',1,'Application::bestFlightAirportToLocation(const std::string &amp;airport, const long double &amp;latitude, const long double &amp;longitude)']]],
  ['bestflightcitytoairport_11',['bestFlightCityToAirport',['../classApplication.html#a8d6aa4a7f90baa2e8e1c0426042b2a0f',1,'Application::bestFlightCityToAirport(const std::string &amp;city, const std::string airport, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a87199938224b3d752f92689fb369f629',1,'Application::bestFlightCityToAirport(const std::string &amp;city, const std::string airport)']]],
  ['bestflightcitytocity_12',['bestFlightCityToCity',['../classApplication.html#a2856f438efc305bb3dd02d29faa999c5',1,'Application::bestFlightCityToCity(const std::string &amp;sourceCity, const std::string &amp;destinationCity, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a21f701c9968bcaacd2da197fd7b039b9',1,'Application::bestFlightCityToCity(const std::string &amp;sourceCity, const std::string &amp;destinationCity)']]],
  ['bestflightcitytolocation_13',['bestFlightCityToLocation',['../classApplication.html#a20c160beb5f6bba2a413e8c2baaf2f19',1,'Application::bestFlightCityToLocation(const std::string &amp;city, const long double &amp;latitude, const long double &amp;longitude, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a2492cbac9b43ed2eed83bc9a0cb82dc0',1,'Application::bestFlightCityToLocation(const std::string &amp;city, const long double &amp;latitude, const long double &amp;longitude)']]],
  ['bestflightlocationtoairport_14',['bestFlightLocationToAirport',['../classApplication.html#a54a7f46c42d89406bd9f218cc896fdf6',1,'Application::bestFlightLocationToAirport(const long double &amp;latitude, const long double &amp;longitude, const std::string &amp;airport, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a75f3b68db2b1d9266e3da6f28ede41ae',1,'Application::bestFlightLocationToAirport(const long double &amp;latitude, const long double &amp;longitude, const std::string &amp;airport)']]],
  ['bestflightlocationtocity_15',['bestFlightLocationToCity',['../classApplication.html#a2bceba75383f08833bcfe0ba5fc9400a',1,'Application::bestFlightLocationToCity(const long double &amp;latitude, const long double &amp;longitude, const std::string &amp;city, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a14ec9d0c3a2c255dd2c003cfa6231262',1,'Application::bestFlightLocationToCity(const long double &amp;latitude, const long double &amp;longitude, const std::string &amp;city)']]],
  ['bestflightlocationtolocation_16',['bestFlightLocationToLocation',['../classApplication.html#ab753b5d45b55613f0af83ddb17c2a535',1,'Application::bestFlightLocationToLocation(const long double &amp;sourceLatitude, const long double &amp;sourceLongitude, const long double &amp;destLatitude, const long double &amp;destLongitude, const std::vector&lt; Airline &gt; &amp;forbidden)'],['../classApplication.html#a6b06613dd5aad2f4f32e9b5578301ef0',1,'Application::bestFlightLocationToLocation(const long double &amp;sourceLatitude, const long double &amp;sourceLongitude, const long double &amp;destLatitude, const long double &amp;destLongitude)']]],
  ['bfs_17',['bfs',['../classGraph.html#a6cf5090909c58407eea67bca8662ca02',1,'Graph']]],
  ['bfsfurthestvertices_18',['bfsFurthestVertices',['../classGraph.html#afc1b9b9cc386414c6bcafd26cba6eaff',1,'Graph']]],
  ['bfsshortestpath_19',['bfsShortestPath',['../classGraph.html#a025c2a748bfd07b81fc106e7d1211c32',1,'Graph::bfsShortestPath(const Airport &amp;source, const Airport &amp;destination) const'],['../classGraph.html#abf31bab448dc4f68800d0c3b64889b96',1,'Graph::bfsShortestPath(std::shared_ptr&lt; Vertex &gt; source, std::shared_ptr&lt; Vertex &gt; destination) const'],['../classGraph.html#a474a159074dd5c0898fd202292748d3c',1,'Graph::bfsShortestPath(const Airport &amp;source, const Airport &amp;destination, const std::vector&lt; Airline &gt; forbidden) const'],['../classGraph.html#a15654de421eabd40e37de40dbc31b220',1,'Graph::bfsShortestPath(shared_ptr&lt; Vertex &gt; source, shared_ptr&lt; Vertex &gt; destination, const std::vector&lt; Airline &gt; forbidden) const']]],
  ['bfswithsteps_20',['bfsWithSteps',['../classGraph.html#a5d87496ec5065107c93e9e77cd03821a',1,'Graph']]]
];
